# These are the see counterparts, we'll look for English counterparts to these German subs
dataset_name: 'German subreddit seeds for counterparts'
bucket_name: 'i18n-subreddit-clustering'
folder_data_prefix: 'data/subreddit_counterparts'

f_seeds: 'Criteria for default subs - [OLD]default subs-2021-08-13_15-17.csv'
f_skiprows: 3
