# These are the ad-hoc clustering outputs used to create the v0.3.2_a tables
dataset_name: 'Top Subreddits (no Geo) + German Subs 2021-07-16, comments: 2021-07-09'
bucket_name: 'i18n-subreddit-clustering'
folder_model_outputs: 'data/models/clustering/manual_2021-08-11_04_45'

f_subs_agg_c_cluster_labels: 'df_subs_only-meta_and_multiple_clustering_algos-2021-08-13_022453-3767_by_58.parquet'
f_subs_agg_c_similarity_pair: 'df_sub_level_agg_c_similarity_pair-2021-08-13_021828-14186522_by_18.parquet'

col_best_clusters_a: 'cluster_id_agg_ward_cosine_200'
