min_post_and_comment_text_len: 3

agg_post_post_and_comment_weight: 85
agg_post_subreddit_desc_weight: 15

# TODO(djb): do a weighted average with these columns
#  HOWEVER, if these are null, then we'll simply do a regular mean
# agg_comments_to_post_weight_col: null  # 'comment_text_len'?
# agg_post_to_subreddit_weight_col: null
