config_description: "Config to do a simple test to vectorize subreddit descriptions"
defaults:
  - data_text: subreddits_sql_test.yaml

model_name: use_multilingual_3

# Keys for items to vectorize should match keys in data_text
thing_to_vectorize: subreddit_meta
col_text_for_embeddings: concat_text

output_bucket: 'gazette-models-temp'
output_folders:
  subreddit_meta: 'i18n_topic_model/subreddits/test'
  posts: 'i18n_topic_model/posts/test'
  comments: 'i18n_topic_model/comments/test'



# Change n_jobs(parallel jobs) & logging for hydra itself
hydra:
  # launcher:
    # override the number of jobs for joblib
    # n_jobs: 11
  job_logging:
    formatters:
      simple:
        # format: '`%(asctime)s` | `%(name)s` | `%(levelname)s` | `%(message)s`'
        format: '`%(asctime)s` | `%(levelname)s` | `%(message)s`'
  # Change location of logging - by default it might try to create logs in
  #  home/david.bermejo instead of home/jupyter
  #  https://hydra.cc/docs/configure_hydra/workdir/
  run:
    dir: /home/jupyter/subreddit_clustering_i18n/hydra_runs/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: /home/jupyter/subreddit_clustering_i18n/hydra_runs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
