# embeddings_description: 'Embeddings from USE-multilingual with lower_case=False'
comments_uuid: ['5f10cd75334142168a6ebb787e477c1f', '2fcfefc3d5af43328168d3478b4fdeb6']
comments_folder_embeddings: 'df_vect_comments'
col_comment_id: 'comment_id'
col_text_comment_word_count: 'comment_text_word_count'

posts_uuid: '8eef951842a34a6e81d176b15ae74afd'
posts_folder_embeddings: 'df_vect_posts'
col_text_post_word_count: 'text_word_count'
col_post_id: 'post_id'

subreddit_desc_uuid: '8eef951842a34a6e81d176b15ae74afd'
subreddit_desc_folder_embeddings: 'df_vect_subreddits_description'
col_subreddit_id: 'subreddit_id'
