# embeddings_description: 'Embeddings from USE-multilingual with lower_case=False'
comments_uuid: [
    '26c8fcf422a9403ba4a844c8e380bf7f',
    '54ba724869bf4ec9a2cad2a4f7eca048',
    'e7ed11ccdc0b45abbdf3bf19605d4498',
    'a69d1b259875458283124ffdaa6efbb6'
]
comments_folder_embeddings: 'df_vect_comments'
col_comment_id: 'comment_id'
col_text_comment_word_count: 'comment_text_word_count'

posts_uuid: '559a8f13264245b3923ab5699ef55bfe'
posts_folder_embeddings: 'df_vect_posts_extra_text'
col_text_post_word_count: 'text_word_count'
col_post_id: 'post_id'

subreddit_desc_uuid: '559a8f13264245b3923ab5699ef55bfe'
subreddit_desc_folder_embeddings: 'df_vect_subreddits_description'
col_subreddit_id: 'subreddit_id'
