description: "Base config to test FPR creation"

output_bucket: 'i18n-subreddit-clustering'
gcs_output_path: 'i18n_topic_model_batch/fpr/runs'
add_outputs_to_bq: True

cluster_labels_table: "reddit-employee-datasets.david_bermejo.subclu_v0050_subreddit_clusters_c_full"
partition_dt: "2022-08-02"
qa_table: "reddit-employee-datasets.david_bermejo.subclu_v0050_subreddit_clusters_c_qa_flags"
qa_pt: "2022-08-02"

geo_relevance_table: "reddit-employee-datasets.david_bermejo.subclu_subreddit_relevance_beta_20220725"
geo_min_users_percent_by_subreddit_l28: 0.14
geo_min_country_standardized_relevance: 2.9

target_countries:
  - CA
  - GB
  - AU
