description: "Use this config to reshape embeddings and upload them to BigQuery"
defaults:
  - data_text_and_metadata:  v0.6.0_model
  - data_embeddings_to_aggregate: v0.6.0_2022-08-15_muse_lower_case_false
  - aggregate_params: v0.6.0_agg

bucket_output: 'i18n-subreddit-clustering'
mlflow_tracking_uri: 'sqlite'
mlflow_run_id: 'badc44b0e5ac467da14f710da0b410c6'
embeddings_artifact_path: 'df_subs_agg_c1_unweighted'

bq_project: 'reddit-employee-datasets'
bq_dataset: 'david_bermejo'
bq_table: 'cau_subreddit_embeddings'

pt: '2022-08-11'  # Date original text was pulled
model_version: 'v0.6.0'
model_name: 'cau-text-mUSE-embeddings'
embeddings_config: aggregate_embeddings_v0.6.0
