description: "Use this config to reshape embeddings and upload them to BigQuery"
defaults:
  - data_text_and_metadata:  v0.6.1_model
  - data_embeddings_to_aggregate: v0.6.1_2022-11-07_muse_lower_case_false
  - aggregate_params: v0.6.1_agg

bucket_output: 'i18n-subreddit-clustering'
mlflow_tracking_uri: 'sqlite'
mlflow_run_id: '91ac7ca171024c779c0992f59470c81b'
embeddings_artifact_path: 'df_subs_agg_c1_unweighted'

bq_project: 'reddit-employee-datasets'
bq_dataset: 'david_bermejo'
bq_table: 'cau_subreddit_embeddings'
bq_table_description: "Subreddit-level embeddings. See the wiki for more details. https://reddit.atlassian.net/wiki/spaces/DataScience/pages/2404220935/"
update_table_description: True,

pt: '2022-11-07'  # Date original text was pulled
model_version: 'v0.6.1'
model_name: 'cau-text-mUSE'
embeddings_config: aggregate_embeddings_v0.6.1
