dataset_name: 'v0.6.0 inputs. ~110k seed subreddits, ~340k with 3+ posts, ~700k total subreddits'
bucket_name: 'i18n-subreddit-clustering'

# Alt = ran on a different day, but with the same partition parameters
folder_subreddits_text_and_meta: 'i18n_topic_model_batch/runs/20220811/subreddits/text'
folder_posts_text_and_meta: 'i18n_topic_model_batch/runs/20220811/posts'
folder_comments_text_and_meta: 'i18n_topic_model_batch/runs/20220811/comments'

folder_post_and_comment_text_and_meta: 'i18n_topic_model_batch/runs/20220811/post_and_comment_text_combined/text_all'
