model_name: 'AgglomerativeClustering'  # pull from the clustering_registry

# Pass these kwargs to the model defined by the key in the clustering_registry
model_kwargs:
  n_clusters: 100
  affinity: 'euclidean'
  linkage: 'ward'
  connectivity: false
